### ISSUE TITLE
Dependency "ruckig" needed since version 1.1.11

### ISSUE THREAD

**Issue by lprobsth** [ros-noetic-arch/ros-noetic-moveit-core#3]
This package was flagged outdated.
The current version targets upstream version 1.1.8.
Currently version 1.1.13 is available upstream.

For updating moveit_core to the newest version the dependency "ruckig" (https://github.com/pantor/ruckig) has to be released in the AUR first, since it's an dependency since version 1.1.11.

**Comment by acxz** [comment]
Thanks for the report @lprobsth, added with [d9b4783](https://github.com/ros-noetic-arch/ros-noetic-moveit-core/commit/d9b47835ccd82c2a8537d3a52605429215f68ba3)
